require('dotenv').config();
const db = require('./db');

function getConfig() {
    const dbConfig = db.getConfig();
    return {
        BOT_RUNNING_STATE: dbConfig.BOT_RUNNING_STATE || 'false',
        WEBUI_AUTH_ENABLED: dbConfig.WEBUI_AUTH_ENABLED === 'true',
        WEBUI_USERNAME: dbConfig.WEBUI_USERNAME || 'admin',
        WEBUI_PASSWORD: dbConfig.WEBUI_PASSWORD || 'admin',
        API_KEY: dbConfig.API_KEY || '',
        API_SECRET: dbConfig.API_SECRET || '',
        ENABLE_VWAP_STRATEGY: dbConfig.ENABLE_VWAP_STRATEGY === 'true',
        VWAP_TYPE: dbConfig.VWAP_TYPE || 'rolling',
        VWAP_SESSION_TYPE: dbConfig.VWAP_SESSION_TYPE || 'daily',
        VWAP_PERIOD: parseInt(dbConfig.VWAP_PERIOD) || 14,
        VWAP_TIMEFRAME: dbConfig.VWAP_TIMEFRAME || '1m',
        ENABLE_RSI_STRATEGY: dbConfig.ENABLE_RSI_STRATEGY === 'true',
        ENABLE_MARKET_SENTIMENT_STRATEGY: dbConfig.ENABLE_MARKET_SENTIMENT_STRATEGY === 'true',
        RSI_PERIOD: parseInt(dbConfig.RSI_PERIOD) || 14,
        RSI_TIMEFRAME: dbConfig.RSI_TIMEFRAME || '1m',
        RSI_OVERBOUGHT: parseFloat(dbConfig.RSI_OVERBOUGHT) || 70,
        RSI_OVERSOLD: parseFloat(dbConfig.RSI_OVERSOLD) || 30,
        ENABLE_DMI_STRATEGY: dbConfig.ENABLE_DMI_STRATEGY === 'true',
        DMI_PERIOD: parseInt(dbConfig.DMI_PERIOD) || 14,
        DMI_TIMEFRAME: dbConfig.DMI_TIMEFRAME || '1m',
        DMI_THRESHOLD: parseFloat(dbConfig.DMI_THRESHOLD) || 25,
        TRADE_EXCHANGE: dbConfig.TRADE_EXCHANGE || 'bybit',
        LIQUIDATION_EXCHANGES: dbConfig.LIQUIDATION_EXCHANGES || 'bybit',
        LIQUIDATION_VALUE_CURRENCY: dbConfig.LIQUIDATION_VALUE_CURRENCY || 'USD',
        LIQUIDATION_VALUE_THRESHOLD: parseFloat(dbConfig.LIQUIDATION_VALUE_THRESHOLD) || 1000,
        OFFSET_LONG_PERCENTAGE: parseFloat(dbConfig.OFFSET_LONG_PERCENTAGE) || 0.5,
        OFFSET_SHORT_PERCENTAGE: parseFloat(dbConfig.OFFSET_SHORT_PERCENTAGE) || 0.5,
        TAKE_PROFIT_PERCENTAGE: parseFloat(dbConfig.TAKE_PROFIT_PERCENTAGE) || 1.0,
        STOP_LOSS_PERCENTAGE: parseFloat(dbConfig.STOP_LOSS_PERCENTAGE) || 0.5,
        ENABLE_TRAILING_PROFIT: dbConfig.ENABLE_TRAILING_PROFIT === 'true',
        TRAILING_PROFIT_PERCENTAGE: parseFloat(dbConfig.TRAILING_PROFIT_PERCENTAGE) || 0.2,
        TRAILING_ACTIVATION_PERCENTAGE: parseFloat(dbConfig.TRAILING_ACTIVATION_PERCENTAGE) || 0.0,
        TRADE_LEVERAGE: parseInt(dbConfig.TRADE_LEVERAGE) || 10,
        TRADE_AMOUNT_PERCENTAGE: parseFloat(dbConfig.TRADE_AMOUNT_PERCENTAGE) || 5,
        MAX_OPEN_POSITIONS: parseInt(dbConfig.MAX_OPEN_POSITIONS) || 3,
        ENABLE_ISOLATION_MODE: dbConfig.ENABLE_ISOLATION_MODE === 'true',
        ISOLATION_MARGIN_THRESHOLD: parseFloat(dbConfig.ISOLATION_MARGIN_THRESHOLD) || 10,
        REDUCE_TP_TRAILING_BY_HALF_IN_ISOLATION: dbConfig.REDUCE_TP_TRAILING_BY_HALF_IN_ISOLATION === 'true',
        CMC_API_KEY: dbConfig.CMC_API_KEY || '',
        CMC_RANK_LIMIT: parseInt(dbConfig.CMC_RANK_LIMIT) || 100,
        CMC_FILTER_ENABLED: dbConfig.CMC_FILTER_ENABLED === 'true',
        ENABLE_DCA_MARTINGALE: dbConfig.ENABLE_DCA_MARTINGALE === 'true',
        DCA_MARTINGALE_THRESHOLD: parseFloat(dbConfig.DCA_MARTINGALE_THRESHOLD) || -5,
        DCA_MARTINGALE_MAX_MULTIPLIER: parseInt(dbConfig.DCA_MARTINGALE_MAX_MULTIPLIER, 10) || 5,
        ENABLE_DYNAMIC_THRESHOLDS: dbConfig.ENABLE_DYNAMIC_THRESHOLDS === 'true',
        REPLACE_BELOW_MIN_THRESHOLD: dbConfig.REPLACE_BELOW_MIN_THRESHOLD === 'true',
        ENABLE_RUNAWAY_HELPER: dbConfig.ENABLE_RUNAWAY_HELPER === 'true',
        RUNAWAY_HELPER_THRESHOLD: parseFloat(dbConfig.RUNAWAY_HELPER_THRESHOLD) || -10,
        ENABLE_AUTO_TRANSFER: dbConfig.ENABLE_AUTO_TRANSFER === 'true',
        MIN_BALANCE_THRESHOLD: parseFloat(dbConfig.MIN_BALANCE_THRESHOLD) || 1000,
        TRANSFER_PERCENTAGE_THRESHOLD: parseFloat(dbConfig.TRANSFER_PERCENTAGE_THRESHOLD) || 5,
        RAPIDAPI_KEY: dbConfig.RAPIDAPI_KEY || '',
        COIN_BLACKLIST: dbConfig.COIN_BLACKLIST || '',
        VWAP_UPPER_SIGNAL: dbConfig.VWAP_UPPER_SIGNAL || 'sell',
        VWAP_LOWER_SIGNAL: dbConfig.VWAP_LOWER_SIGNAL || 'buy',
        RSI_OVERBOUGHT_DIR: dbConfig.RSI_OVERBOUGHT_DIR || 'above',
        RSI_OVERBOUGHT_SIGNAL: dbConfig.RSI_OVERBOUGHT_SIGNAL || 'sell',
        RSI_OVERSOLD_DIR: dbConfig.RSI_OVERSOLD_DIR || 'under',
        RSI_OVERSOLD_SIGNAL: dbConfig.RSI_OVERSOLD_SIGNAL || 'buy',
        RSI_BYPASS_ON_POSITION: dbConfig.RSI_BYPASS_ON_POSITION || 'false',
        DMI_THRESHOLD_DIR: dbConfig.DMI_THRESHOLD_DIR || 'under',
        DMI_PDI_SIGNAL: dbConfig.DMI_PDI_SIGNAL || 'sell',
        DMI_MDI_SIGNAL: dbConfig.DMI_MDI_SIGNAL || 'buy',
        DMI_BYPASS_ON_POSITION: dbConfig.DMI_BYPASS_ON_POSITION || 'false',
        MS_BULLISH_SIGNAL: dbConfig.MS_BULLISH_SIGNAL || 'buy',
        MS_BEARISH_SIGNAL: dbConfig.MS_BEARISH_SIGNAL || 'sell',
        MS_EXTREME_FEAR_SIGNAL: dbConfig.MS_EXTREME_FEAR_SIGNAL || 'none',
        MS_EXTREME_GREED_SIGNAL: dbConfig.MS_EXTREME_GREED_SIGNAL || 'none',
        MS_BYPASS_ON_POSITION: dbConfig.MS_BYPASS_ON_POSITION || 'false',
        ENABLE_ANON_REPORTING: dbConfig.ENABLE_ANON_REPORTING === 'true',
        ANON_UID: dbConfig.ANON_UID || '',
        ENABLE_24H_VOLUME_FILTER: dbConfig.ENABLE_24H_VOLUME_FILTER === 'true',
        MIN_24H_VOLUME_USD: dbConfig.MIN_24H_VOLUME_USD !== undefined ? parseFloat(dbConfig.MIN_24H_VOLUME_USD) : 1000000,
        MAX_POSITION_SIZE_PERCENTAGE: dbConfig.MAX_POSITION_SIZE_PERCENTAGE !== undefined ? parseFloat(dbConfig.MAX_POSITION_SIZE_PERCENTAGE) : 10,
        LOG_LEVEL: process.env.LOG_LEVEL || 'info',
        WEB_PORT: parseInt(process.env.WEB_PORT) || 3000,
        WEB_HOST: process.env.WEB_HOST || 'localhost',
        ENABLE_CIRCUIT_BREAKER: dbConfig.ENABLE_CIRCUIT_BREAKER === 'true',
        CB_TIMEFRAME: dbConfig.CB_TIMEFRAME || '15m',
        CB_ATR_PERIOD: parseInt(dbConfig.CB_ATR_PERIOD) || 14,
        CB_ATR_MULTIPLIER: parseFloat(dbConfig.CB_ATR_MULTIPLIER) || 3.0,
        CB_PRICE_LOOKBACK: parseInt(dbConfig.CB_PRICE_LOOKBACK) || 10,
        CB_VOLUME_SMA_PERIOD: parseInt(dbConfig.CB_VOLUME_SMA_PERIOD) || 20,
        CB_VOLUME_MULTIPLIER: parseFloat(dbConfig.CB_VOLUME_MULTIPLIER) || 2.0
    };
}

module.exports = {
    get: getConfig,
    set: (key, value) => {
        db.setConfig(key, value);
    }
};
